<?php

namespace Omnipay\Cathaybk\Message;

use Omnipay\Common\Message\AbstractResponse;

class FetchTransactionResponse extends AbstractResponse
{
    private $messages = [
        '0202' => '授權成功',
        '1102' => '已請款未結帳',
        '1702' => '取消請款',
        '1212' => '已請款已結帳',
        '0303' => '授權失敗',
        '2112' => '已退款未結帳',
        '2222' => '已退款已結帳',
        '2322' => '部分退款已結帳',
        '0000' => '訂單初始或 3D 交易驗證中 ',
        '0404' => '取消交易',
        '9901' => '無符合之訂單',
        'E001' => '系統忙碌中',
        'E002' => '系統維護中',
        'E100' => '系統維護中',
        'L001' => '資料格式有誤',
        'L100' => '資料格式有誤',
    ];

    /**
     * Is the response successful?
     *
     * @return bool
     */
    public function isPending()
    {
        return in_array($this->getCode(), ['0000']);
    }

    /**
     * Is the transaction cancelled by the user?
     *
     * @return bool
     */
    public function isCancelled()
    {
        return in_array($this->getCode(), ['0404']);
    }

    /**
     * @return bool
     */
    public function isSuccessful()
    {
        return in_array($this->getCode(), ['0202', '1102', '1212']);
    }

    /**
     * Response code.
     *
     * @return null|string A response code from the payment gateway
     */
    public function getCode()
    {
        return $this->data['CUBXML']['ORDERINFO']['STATUS'];
    }

    /**
     * Gateway Reference.
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference()
    {
        return $this->data['CUBXML']['ORDERINFO']['AUTHCODE'];
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->data['CUBXML']['ORDERINFO']['ORDERNUMBER'];
    }

    /**
     * Response Message.
     *
     * @return string A response message from the payment gateway
     */
    public function getMessage()
    {
        return array_key_exists($this->getCode(), $this->messages)
            ? $this->messages[$this->getCode()]
            : '未定義錯誤';
    }
}
