<?php

namespace Omnipay\Cathaybk\Message;

use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Common\Message\RedirectResponseInterface;

class PurchaseResponse extends AbstractResponse implements RedirectResponseInterface
{
    /**
     * @return bool
     */
    public function isSuccessful()
    {
        return false;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->data['ORDERNUMBER'];
    }

    /**
     * Is the response successful?
     *
     * @return bool
     */
    public function isPending()
    {
        return true;
    }

    /**
     * Does the response require a redirect?
     *
     * @return bool
     */
    public function isRedirect()
    {
        return true;
    }

    /**
     * Gets the redirect target url.
     *
     * @return string
     */
    public function getRedirectUrl()
    {
        return 'https://sslpayment.uwccb.com.tw/EPOSService/Payment/OrderInitial.aspx';
    }

    /**
     * Get the required redirect method (either GET or POST).
     *
     * @return string
     */
    public function getRedirectMethod()
    {
        return 'POST';
    }

    /**
     * Gets the redirect form data array, if the redirect method is POST.
     *
     * @return array
     */
    public function getRedirectData()
    {
        $options = $this->hasPeriodNumber() ? $this->period() : $this->normal();

        return [
            'strRqXML' => Helper::array2xml(['MERCHANTXML' => [
                'CAVALUE' => Helper::signSignature($this->data, $options['signature_keys']),
                'MSGID' => $options['msg_id'],
                'ORDERINFO' => $this->data,
            ]]),
        ];
    }

    /**
     * @return bool
     */
    private function hasPeriodNumber(): bool
    {
        return array_key_exists('PERIODNUMBER', $this->data) && (int) $this->data['PERIODNUMBER'] > 1;
    }

    private function normal()
    {
        return [
            'msg_id' => 'TRS0004',
            'signature_keys' => ['STOREID', 'ORDERNUMBER', 'AMOUNT', 'LANGUAGE', 'CUBKEY'],
        ];
    }

    /**
     * @return array
     */
    private function period()
    {
        return [
            'msg_id' => 'TRS0005',
            'signature_keys' => ['STOREID', 'ORDERNUMBER', 'AMOUNT', 'PERIODNUMBER', 'LANGUAGE', 'CUBKEY'],
        ];
    }
}
