<?php

namespace Omnipay\Cathaybk\Message;

use Omnipay\Common\Message\AbstractResponse;

class VoidResponse extends AbstractResponse
{
    private $messages = [
        'L001' => '資料格式有誤',
        'L100' => '資料格式有誤',
        'L002' => '檢核商家認證資料失敗',
        'L003' => '無符合的可取消資料',
        'L004' => '商家交易網址錯誤',
        'L005' => '主機批次執行中',
        'L006' => '取消授權失敗',
        'L007' => '請洽系統管理員',
        'E001' => '系統忙碌中',
        'E002' => '系統維護中',
        'E100' => '系統維護中',
    ];

    /**
     * Is the response successful?
     *
     * @return boolean
     */
    public function isSuccessful()
    {
        return in_array($this->getCode(), ['0000']);
    }

    /**
     * Response code.
     *
     * @return null|string A response code from the payment gateway
     */
    public function getCode()
    {
        return $this->data['CUBXML']['CANCELORDERINFO']['STATUS'];
    }

    /**
     * Gateway Reference.
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference()
    {
        return $this->data['CUBXML']['CANCELORDERINFO']['AUTHCODE'];
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->data['CUBXML']['CANCELORDERINFO']['ORDERNUMBER'];
    }

    /**
     * Response Message.
     *
     * @return string A response message from the payment gateway
     */
    public function getMessage()
    {
        return array_key_exists($this->getCode(), $this->messages)
            ? $this->messages[$this->getCode()] : '未定義錯誤';
    }
}
